name: Test python

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      matrix:
        python-version: [ 3.8 ]
        include:
          - EXTRAS: "postgresql,tests"
            SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://postgres@localhost:5432/invenio"
          - EXTRAS: "sqlite,tests"

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache pip
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144
      - name: Runs Elasticsearch
        uses: elastic/elastic-github-actions/elasticsearch@master
        with:
          stack-version: 7.6.0
      - name: Before install
        env:
          EXTRAS: $ {{matrix.EXTRAS}}
        run: |
          pip install --upgrade pip setuptools py
          pip install twine wheel coveralls requirements-builder pip-tools
          requirements-builder --level=pypi -e $EXTRAS setup.py > .travis-release-requirements.in
          pip-compile -U --verbose -o .travis-release-requirements.txt .travis-release-requirements.in
          cat .travis-release-requirements.txt
      - name: Install dependencies
        run: |
          pip install -r .travis-release-requirements.txt
      - name: Test with pytest
        env:
          SQLALCHEMY_DATABASE_URI: $ {{matrix.SQLALCHEMY_DATABASE_URI}}
        run: |
          "./run-tests.sh"
#      - name: Check manifest
#        run: |
#          check-manifest
      #
      #    - name: Coveralls
      #      uses: AndreMiras/coveralls-python-action@develop
      #      with:
      #        parallel: true
      #        flag-name: Test with pytest

      #  coveralls_finish:
      #    needs: build
      #    runs-on: ubuntu-latest
      #    steps:
      #      - name: Coveralls Finished
      #        uses: AndreMiras/coveralls-python-action@develop
      #        with:
      #          parallel-finished: true

      - name: Build package to publish
        run: |
          python setup.py sdist bdist_wheel
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Use built artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - name: List files
        run: |
          ls -la
          ls -la dist
      - name: Publish package
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          skip_existing: true
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}